### ISSUE TITLE
requirements.txt missing

### ISSUE THREAD

**Issue by rosiakpiotr** [TMALFSSISAWBOJBUMA/KB_simulator#1]
Hello, I noticed that file with list of python packages (usually `requirements.txt`) is missing from the repository which makes it hard to setup.

Going forward, there is no `README.md` with short description what are objectives of this project and how to use it.

**Comment by pieszke** [comment]
Hi, I added the files you mentioned in 684a0de64b210e0d852cf4342a658a21d490fcbd for your convenience

**Comment by rosiakpiotr** [comment]
Thank you. Please note this contribution is meant to serve wider group than myself and my convenience.
